#ifndef GCCONSTANTS_H
#define GCCONSTANTS_H

#endif // GCCONSTANTS_H

#define kVersionNumber "2.1.1"
#define kVersion "Kick Ass GUI v2.1.1"

#define LOG1 true
#define LOG2 true
#define LOG3 true
#define LOG4 true
#define LOG5 true

#define kKickPath "kickPath"
#define kShaderPath "shaderPath"
#define kLastUsedDirCheckBox "lastUsedDirCheckBox"

#define kLastUsedDirCheckBox "lastUsedDirCheckBox"
#define kLastUsedDir "lastUsedDir"
#define kSequence "sequence"
#define kDisableOutputWindow "disableOutputWindow"
#define kClearOnRender "clearOnRender"
#define kNotifyOnSeqCompletion "notifyOnSeqCompletion"
//#define kDebugMode "debugMode"
#define kResCheckBox "resCheckBox"
#define kResX "resX"
#define kResY "resY"
#define kAACheckBox "aaCheckBox"
#define kAA "aa"
#define kDiffuseSampelsCheckBox "diffuseSamplesCheckBox"
#define kDiffuseSamples "diffuseSamples"
#define kGlossySamplesCheckBox "glossySamplesCheckBox"
#define kGlossySamples "glossySamples"
#define kMotionBlurCheckBox "motionBlurCheckBox"
#define kMotionBlurStart "motionBlurStart"
#define kMotionBlurEnd "motionBlurEnd"
#define kAAFilterCheckBox "aaFilterCheckBox"
#define kAAFilterComboBox "aaFilterComboBox"
#define kAAFilterWidth "aaFilterWidth"
#define kBucketSizeCheckBox "bucketSizeCheckBox"
#define kBucketSize "bucketSize"
#define kBucketScanningCheckBox "bucketScanningCheckBox"
#define kBucketScanning "bucketScanning"
#define kVerboseCheckBox "verboseLevelCheckBox"
#define kVerboseLevel "verboseLevel"
#define kTotalDepthCheckBox "totalDepthCheckBox"
#define kTotalDepth "totalDepth"
#define kDiffuseDepthCheckBox "diffuseDepthCheckBox"
#define kDiffuseDepth "diffuseDepth"
#define kGlossyDepthCheckBox "glossyDepthCheckBox"
#define kGlossyDepth "glossyDepth"
#define kReflectionDepthCheckBox "reflectionDepthCheckBox"
#define kReflectionDepth "reflectionDepth"
#define kRefractionDepthCheckBox "refractionDepthCheckBox"
#define kRefractionDepth "refractionDepth"
#define kOutputGammaCheckBox "outputGammaCheckBox"
#define kOutputGamma "outputGamma"
#define kTextureGammaCheckBox "textureGammaCheckBox"
#define kTextureGamma "textureGamma"
#define kLightGammaCheckBox "lightGammaCheckBox"
#define kLightGamma "lightGamma"
#define kShaderGammaCheckBox "shaderGammaCheckBox"
#define kShaderGamma "shaderGamma"
#define kTextureMapsCheckBox "textureMapsCheckBox"
#define kShadersCheckBox "shadersCheckBox"
#define kBackgroundShadersCheckBox "backgroundShadersCheckBox"
#define kAtmosphereShadersCheckBox "atmosphereShadersCheckBox"
#define kLightsCheckBox "lightsCheckBox"
#define kShadowsCheckBox "shadowsCheckBox"
#define kMeshSubdivisionCheckBox "meshSubdivisionCheckBox"
#define kDisplacementCheckBox "displacementCheckBox"
#define kMotionBlurCheckBox "motionBlurCheckBox"
#define kSSSCheckBox "sssCheckBox"
#define kInteractiveNavCheckBox "interactiveNavCheckBox"
#define kInteractiveNav "interactiveNav"
#define kFlatShadingCheckBox "flatShadingCheckBox"
#define kThreadsCheckBox "threadsCheckBox"
#define kThreads "threads"
#define kCameraCheckBox "cameraCheckBox"
#define kCamera "camera"
#define kProgressiveRenderCheckBox "progressiveRenderCheckBox"
#define kDirectLightingCheckBox "directLightingCheckBox"
